#include "encoder.h"

#include "sysctl.h"
#include "register.h"
#include "gpio.h"

//
// SYSCTL
//

const uint32_t REGISTER_SYSCTL_PERIPHCTL_QEI_OFFSET = 0x44;
const uint32_t REGISTER_SYSCTL_PERIPHCTL_QEI_0_INSTANCEMASK = 0b1 << 0;
const uint32_t REGISTER_SYSCTL_PERIPHCTL_QEI_1_INSTANCEMASK = 0b1 << 1;

//
// GPIO
//

// REGISTER_GPIO_GPIOPCTL_H_PWM_M0
const uint32_t REGISTER_GPIO_GPIOPCTL_G_QEI = 0x06;
const uint32_t REGISTER_GPIO_GPIOPCTL_H_QEI = 0x05;

//
// QEI
//

const uint32_t REGISTER_QEI_QEICTL_OFFSET = 0x0;
const uint32_t REGISTER_QEI_QEICTL_ENABLE = 0b1 << 0;
const uint32_t REGISTER_QEI_QEICTL_CAPMODE_PhA_ONLY = 0b0 << 3;
const uint32_t REGISTER_QEI_QEICTL_CAPMODE_PhA_AND_PhB = 0b1 << 3;

const uint32_t REGISTER_QEI_QEIMAXPOS_OFFSET = 0xC;

volatile uint32_t * const REGISTER_QEI_0_QEICTL = (uint32_t *)(REGISTER_QEI_0_BASE + REGISTER_QEI_QEICTL_OFFSET);
volatile uint32_t * const REGISTER_QEI_0_QEIMAXPOS = (uint32_t *)(REGISTER_QEI_0_BASE + REGISTER_QEI_QEIMAXPOS_OFFSET);

volatile uint32_t * const REGISTER_QEI_1_QEICTL = (uint32_t *)(REGISTER_QEI_1_BASE + REGISTER_QEI_QEICTL_OFFSET);
volatile uint32_t * const REGISTER_QEI_1_QEIMAXPOS = (uint32_t *)(REGISTER_QEI_1_BASE + REGISTER_QEI_QEIMAXPOS_OFFSET);

int8_t encoder_init() {
    sysctl_enablePeripheral(
        REGISTER_SYSCTL_PERIPHCTL_GPIO_OFFSET,
        REGISTER_SYSCTL_PERIPHCTL_GPIO_G_INSTANCEMASK | REGISTER_SYSCTL_PERIPHCTL_GPIO_H_INSTANCEMASK
    );

    sysctl_enablePeripheral(
        REGISTER_SYSCTL_PERIPHCTL_QEI_OFFSET, 
        REGISTER_SYSCTL_PERIPHCTL_QEI_0_INSTANCEMASK | REGISTER_SYSCTL_PERIPHCTL_QEI_1_INSTANCEMASK
    );

    gpio_enableAltPinFunc(REGISTER_GPIO_G_BASE, REGISTER_GPIO_PIN_0 | REGISTER_GPIO_PIN_1, REGISTER_GPIO_GPIOPCTL_G_QEI);
    gpio_enableAltPinFunc(REGISTER_GPIO_H_BASE, REGISTER_GPIO_PIN_4 | REGISTER_GPIO_PIN_5, REGISTER_GPIO_GPIOPCTL_H_QEI);
    
    //If we ever get to 0xFFFFFFFF in the pos register than subtracting INT32_MAX will result in a negative number.
    *REGISTER_QEI_0_QEIMAXPOS = UINT32_MAX - 1;
    *REGISTER_QEI_0_QEICTL |= REGISTER_QEI_QEICTL_ENABLE | REGISTER_QEI_QEICTL_CAPMODE_PhA_AND_PhB;
    *REGISTER_QEI_0_QEIPOS = ENCODER_RESET_VALUE;

    *REGISTER_QEI_1_QEIMAXPOS = UINT32_MAX - 1;
    *REGISTER_QEI_1_QEICTL |= REGISTER_QEI_QEICTL_ENABLE | REGISTER_QEI_QEICTL_CAPMODE_PhA_AND_PhB;
    *REGISTER_QEI_1_QEIPOS = ENCODER_RESET_VALUE;
     
    // > mrw 0x4002C000
    // 0x9
    // > mrw 0x4002C00c
    // 0xffffffff
    // > mrw 0x4002C010
    // 0x0

    return 0;
}
